language: rust
rust:
  - stable
  - nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8

script:
  - cargo build --verbose
  - cargo test --verbose
  - make -C examples
