language: rust
rust:
  - stable
  - nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

env:
  global:
    - CXX=g++-5

script:
  - cargo build --verbose
  - cargo test --verbose
  - make -C examples
