language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx
  - windows
  
env:
  matrix:
    - RELEASE= FEATURES=
    - RELEASE=--release FEATURES=
    - RELEASE= FEATURES=--all-features
    - RELEASE=--release FEATURES=--all-features

script:
  - cargo test --all --verbose $RELEASE $FEATURES
  - cargo doc --package mp4parse_capi
