language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx
  - windows
  
env:
  matrix:
    - RELEASE=
    - RELEASE=--release

script:
  # We cannot run `cargo test` with the mp4parse_infallible feature enabled
  # (see comment where the feature is defined in Cargo.toml), but we can at
  # least check for changes behind features that would break the build.
  - cargo check --all --verbose $RELEASE --tests --all-features
  - cargo test --all --verbose $RELEASE
  - cargo doc --package mp4parse_capi
